- name: Install flatpak packages
  community.general.flatpak:
    name:
      - Extensions
      - AnyDesk
      - calibre
      - Discord
      - Flatseal
      - FreeTube
      - Jellyfin Media Player
      - KeePassXC
      - Microsoft Teams
      - mpv
      - Parsec
      - Syncthing GTK
      - Thunderbird
      - Tremotesf
    state: present
