- name: Install flatpak packages
  community.general.flatpak:
    name:
      - AnyDesk
      - Discord
      - Extensions
      - Flatseal
      - FreeTube
      - Jellyfin Media Player
      - KeePassXC
      - Microsoft Teams
      - Parsec
      - Syncthing GTK
      - Telegram Desktop
      - Thunderbird
      - Tremotesf
      - calibre
      - mpv
    state: present
