- name: Add flathub to user
  community.general.flatpak_remote:
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    method: user
    name: flathub
    state: present

- name: Install flatpak packages
  include_tasks: flatpak.yaml
  loop: "{{ app_list | dict2items }}"
