# # NOT WORKING
# - name: Overlay software
#   community.general.rpm_ostree_pkg:
#     name:
#       - docker-compose
#       - gnome-tweaks
#       - moby-engine
#       - ffmpeg-libs
#       - fish
#       - gnome-tweaks
#       - moby-engine
#       - python-psutil
#       - tmux
#     state: present
# # NOT WORKING EITHER
# - name: Install software
#   ansible.builtin.command:
#     argv:
#       - /usr/bin/rpm-ostree
#       - install
#       - docker-compose
#       - ffmpeg-libs
#       - fish
#       - gnome-tweaks
#       - moby-engine
#       - python-psutil
#       - tmux
- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
