- name: Overlay software
  community.general.rpm_ostree_pkg:
    name:
      - docker-compose
      - ffmpeg-libs
      - fish
      - gnome-tweaks
      - gnome-tweaks
      - moby-engine
      - moby-engine
      - openssl
      - python-psutil
      - tmux
      - wireguard-tools
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
